/* eslint-disable react/jsx-key */
/* eslint-disable react-hooks/rules-of-hooks */
/* eslint-disable @next/next/no-img-element */
import React from "react";
import Head from "next/head";
import style from "@/styles/pages/myBagStyle.module.scss";
import Link from "next/link";
import Navbar from "@/components/organisms/navbar";
import CardSelectProduct from "@/components/molecules/cardSelectProduct";

export default function bag() {
  const [bagList, setBagList] = React.useState([
    {
      nameProduk: "jacket",
      brand: "Zalora Cloth",
      img: "/images/product.webp",
      total: 1,
      price: 30000,
    },
  ]);
  return (
    <>
      <Head>
        <title>My Bag | Blanja</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <div className="container-fluid p-0">
          {/* NAVBAR */}
          <nav
            className={`container-fluid sticky-sm-top shadow py-2 ${style.containerNavbar}`}
          >
            <Navbar />
          </nav>
          {/* END OF NAVBAR */}

          {/* MY BAG */}
          <section className={`container ${style.bag}`}>
            <div className={`${style.subTitle}`}>
              <h3>My bag</h3>
            </div>
            <div className={`row ${style.listProduct}`}>
              {/* SIDE LEFT */}
              <div className="col-8">
                {/* SELECT ALL PRODUCT */}
                <div
                  className={`shadow-sm pt-3 px-4 border mt-3 mb-4 ${style.cardSelectAll}`}
                  style={{ width: "100%" }}
                >
                  <div className={`row`}>
                    <div className="col-7">
                      <div class="form-check">
                        <input
                          className="form-check-input"
                          type="checkbox"
                          value=""
                          id="selectAll"
                        />
                        <label
                          className="form-check-label d-inline-block"
                          for="selectAll"
                        >
                          Select all items{" "}
                          <p className="d-inline-block">(2 items selected)</p>
                        </label>
                      </div>
                    </div>
                    <div className="col-5 text-end">
                      <button>Deleted</button>
                    </div>
                  </div>
                </div>
                {/* PRODUCT */}
                {bagList.map((item, key) => {
                  return (
                    <CardSelectProduct
                      {...item}
                      handleOnIncrease={() => {
                        const changeBag = bagList.map((_item, _key) => {
                          if (_key === key) {
                            return { ...item, ...{ total: 1 + item.total } };
                          } else {
                            return item;
                          }
                        });
                        setBagList(changeBag);
                      }}
                      handleOnDecrease={() => {
                        if (item.total > 1) {
                          const changeBag = bagList.map((_item, _key) => {
                            if (_key === key) {
                              return { ...item, ...{ total: item.total - 1 } };
                            } else {
                              return item;
                            }
                          });
                          setBagList(changeBag);
                        }
                      }}
                    />
                  );
                })}
              </div>
              {/* SIDE RIGHT */}
              <div className="col-4">
                <div
                  className={`shadow-sm py-4 px-4 border mt-3 mb-4 ${style.cardCost}`}
                  style={{ width: "100%" }}
                >
                  <h5>Shopping summary</h5>
                  <div className="row mt-4 mb-2">
                    <div className="col-6">
                      <p>Total price</p>
                    </div>
                    <div className="col-6">
                      <h5 className="text-end">$ 40.0</h5>
                    </div>
                  </div>
                  <div className="row">
                    <div className="col-12">
                      <Link
                        href={"/checkout"}
                        type="button"
                        className={`btn btn-primary ${style.btnBuy}`}
                      >
                        Buy
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* <div
              className="movie-selected ps-5 pt-4 pb-4 pe-4 shadow-sm"
              style={{ width: "100%" }}
            >
              <div className="row">
                <div className="col-6">
                  <h5 className="movie-title mt-1">Spider-Man: Homecoming</h5>
                </div>
                <div className="col-3 offset-3">
                  <Link href={"/View-all"}>
                    <button
                      type="button"
                      className="btn btn-primary change-movie"
                    >
                      Change movie
                    </button>
                  </Link>
                </div>
              </div>
            </div> */}
          </section>
          {/* END OF MY BAG */}
        </div>
      </main>
    </>
  );
}
