/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import style from "@/styles/pages/loginStyle.module.scss";
import Link from "next/link";

export default function RegSeller() {
  return (
    <>
      <Head>
        <title>Login | Blanja</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <section className={`container-fluid ${style.register}`}>
          <div className="container">
            <div className={`row`}>
              <div className={`col-12 ${style.col}`}>
                {/* ICON */}
                <div className={`${style.icon}`}>
                  <img src="/images/icon-app.webp" alt="icon-app" />
                </div>
                <div className={`${style.order}`}>
                  <h5>Please login with your account</h5>
                </div>
                <div className={`${style.btn}`}>
                  <div
                    className="btn-group"
                    role="group"
                    aria-label="Basic radio toggle button group"
                  >
                    <Link
                      href={"/auth/login/customer"}
                      className={`btn btn-outline-primary rounded-start ${style.btnCustomer}`}
                    >
                      Customer
                    </Link>
                    <button
                      type="button"
                      className={`btn btn-primary rounded-end ${style.btnSeller}`}
                    >
                      Seller
                    </button>
                  </div>
                </div>
                <div className={`${style.form}`}>
                  <form>
                    <div className="mb-3">
                      <input
                        type="email"
                        class="form-control"
                        id="email"
                        aria-describedby="emailHelp"
                        placeholder="Email"
                        // onChange={(e) => setEmail(e.target.value)}
                      />
                    </div>
                    <div className="mb-3">
                      <input
                        type="password"
                        class="form-control"
                        id="phone"
                        aria-describedby="emailHelp"
                        placeholder="Password"
                        // onChange={(e) => setPhone_number(e.target.value)}
                      />
                    </div>
                    <p className="text-end">Forgot password?</p>
                  </form>
                </div>
                <div className={`d-grid gap-2 mb-4 ${style.btnLogin}`}>
                  <button
                    className="btn btn-warning"
                    type="button"
                    // onClick={handleSubmit}
                    // disabled={isLoading}
                  >
                    Login
                  </button>
                </div>
                <div className={`register ${style.register}`}>
                  <p className="text-center">
                    Dont have a Tokopedia account?{" "}
                    <Link
                      href={"/auth/register/seller"}
                      className={`${style.linkLogin}`}
                    >
                      Register
                    </Link>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
