/* eslint-disable @next/next/no-img-element */
import React from "react";
import Head from "next/head";
import style from "@/styles/pages/filterStyle.module.scss";
import Link from "next/link";
import Navbar from "@/components/organisms/navbar";
import CardProduct from "@/components/molecules/cardProductNew";
import Footer from "@/components/organisms/footer";

export default function DetailProduct() {
  // const [bagList, setBagList] = React.useState([
  //   {
  //     nameProduk: "jacket",
  //     brand: "Zalora Cloth",
  //     img: "/images/product.webp",
  //     total: 1,
  //     price: 30000,
  //   },
  // ]);
  return (
    <>
      <Head>
        <title>Home Filter | Blanja</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <div className="container-fluid p-0">
          {/* NAVBAR */}
          <nav
            className={`container-fluid sticky-sm-top shadow py-2 ${style.containerNavbar}`}
          >
            <Navbar />
          </nav>
          {/* END OF NAVBAR */}

          {/* CONTENT PRODUCT */}
          <section className={`container py-5 ${style.content}`}>
            {/* BREADCRUMB */}
            <nav aria-label="breadcrumb" className={`${style.breadcrumb}`}>
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                  <a href="#">category</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  T-Shirt
                </li>
              </ol>
            </nav>

            {/* FILTERS RESULTS */}
            <div className={`row ${style.content}`}>
              <div className={`${style.subTitle}`}>
                <h2>T-Shirt</h2>
              </div>
              <div className="col-3">
                <CardProduct />
              </div>
              <div className="col-3">
                <CardProduct />
              </div>
              <div className="col-3">
                <CardProduct />
              </div>
              <div className="col-3">
                <CardProduct />
              </div>
            </div>
          </section>
          {/* END OF CONTENT PRODUCT */}

          {/* FOOTER */}
          <Footer />
          {/* END OF FOOTER */}
        </div>
      </main>
    </>
  );
}
