/* eslint-disable react/jsx-key */
/* eslint-disable react-hooks/rules-of-hooks */
/* eslint-disable @next/next/no-img-element */
import React from "react";
import Head from "next/head";
import style from "@/styles/pages/checkoutStyle.module.scss";
import Link from "next/link";
import Navbar from "@/components/organisms/navbar";
import CardCheckout from "@/components/molecules/cardCheckout";
import { useRouter } from "next/router";
import { useSelector } from "react-redux";
import { getCookies, getCookie, setCookie, deleteCookie } from "cookies-next";
import axios from "axios";
import profile from "./user/profile";

export default function bag(props) {
  const checkoutData = useSelector((state) => state);

  const [getProfileData, setGetProfileData] = React.useState(null);
  const [token, setToken] = React.useState(null);
  const [getCheckout, setGetCheckout] = React.useState(
    checkoutData.checkout.data.data
  );

  React.useEffect(() => {
    setToken(props.token);
    setGetProfileData(props.profileData);
  }, []);
  console.log("getCheckout---", getCheckout);
  // console.log("setGetProfileData---", getProfileData);
  return (
    <>
      <Head>
        <title>Payment | Blanja</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <div className="container-fluid p-0">
          {/* NAVBAR */}
          <nav
            className={`container-fluid sticky-sm-top shadow py-2 ${style.containerNavbar}`}>
            <Navbar />
          </nav>
          {/* END OF NAVBAR */}

          {/* MY BAG */}
          <section className={`container ${style.bag}`}>
            <div className={`${style.subTitle}`}>
              <h3>Checkout</h3>
              <p>Shipping Adress</p>
            </div>
            <div className={`row ${style.listProduct}`}>
              {/* SIDE LEFT */}
              <div className="col-8">
                {/* SELECT ALL PRODUCT */}
                <div
                  className={`shadow-sm py-3 px-4 border mb-4 ${style.cardSelectAll}`}
                  style={{ width: "100%" }}>
                  <p className={style.subTitle}>Andreas Jane</p>
                  <p>
                    Perumahan Sapphire Mediterania, Wiradadi, Kec. Sokaraja,
                    Kabupaten Banyumas, Jawa Tengah, 53181 [Tokopedia Note: blok
                    c 16] Sokaraja, Kab. Banyumas, 53181
                  </p>
                  <Link
                    href={""}
                    type="button"
                    className={`btn btn-outline-secondary rounded-pill me-3 ${style.btnAddress}`}>
                    Choose another address
                  </Link>
                </div>
                {/* PRODUCT */}
                {getCheckout.map((item, key) => {
                  const capitalize = (str) => {
                    return str.replace(/(^\w|\s\w)/g, function (letter) {
                      return letter.toUpperCase();
                    });
                  };
                  const prices = price.toString();
                  const convertPrice = prices.replace(
                    /\d(?=(\d{3})+$)/g,
                    "$&."
                  );

                  return (
                    <React.Fragment key={key}>
                      <CardCheckout
                        img={item?.product_picture}
                        selectedProductName
                        selectedColor
                        selectedSize
                        brand
                        totalPrice
                      />
                    </React.Fragment>
                  );
                })}
              </div>
              {/* SIDE RIGHT */}
              <div className="col-4">
                <div
                  className={`shadow-sm py-4 px-4 border mb-4 ${style.cardCost}`}
                  style={{ width: "100%" }}>
                  <h5>Shopping summary</h5>
                  <div className="border-bottom border-4">
                    <div className={`row ${style.order}`}>
                      <div className="col-6">
                        <p>Order</p>
                      </div>
                      <div className="col-6">
                        <h5 className="text-end">Rp.250000</h5>
                      </div>
                    </div>
                    <div className="row">
                      <div className="col-6">
                        <p>Delivery</p>
                      </div>
                      <div className="col-6">
                        <h5 className="text-end">Rp.15000</h5>
                      </div>
                    </div>
                  </div>
                  <div className="pt-3">
                    <div className={`row ${style.totalPrice}`}>
                      <div className="col-7">
                        <h5>Shopping summary</h5>
                      </div>
                      <div className="col-5">
                        <h5 className={`text-end ${style.total}`}>Rp.265000</h5>
                      </div>
                    </div>
                  </div>
                  <div className="row mt-2">
                    <div className="col-12">
                      <Link
                        href={""}
                        type="button"
                        className={`btn btn-primary ${style.btnBuy}`}
                        data-bs-toggle="modal"
                        data-bs-target="#modalCheckout">
                        Select payment
                      </Link>
                      <div
                        className="modal fade"
                        id="modalCheckout"
                        data-bs-backdrop="static"
                        data-bs-keyboard="false"
                        tabindex="-1"
                        aria-labelledby="staticBackdropLabel"
                        aria-hidden="true">
                        <div className="modal-dialog modal-dialog-scrollable shadow-lg">
                          <div className={`modal-content ${style.modal}`}>
                            <div class="modal-header">
                              <button
                                type="button"
                                className="btn-close me-2"
                                data-bs-dismiss="modal"
                                aria-label="Close"></button>
                              <h1
                                className={`modal-title ${style.titleModal}`}
                                id="staticBackdropLabel">
                                Payment
                              </h1>
                            </div>

                            {/* CONTENT MODAL */}
                            <div className="modal-body">
                              {/* PAYMENT OPTION */}
                              <div
                                className={`py-2 px-2 border-bottom border-3 ${style.paymentMethod}`}>
                                <h5 className={`${style.subTitle}`}>
                                  Payment method
                                </h5>
                                {/* GOPAY */}
                                <div
                                  className={`row mt-3 ${style.optionPayment}`}>
                                  <div className={`col-3`}>
                                    <img
                                      className={style.iconGopay}
                                      src="/images/gopay.webp"
                                      alt="icon-navbar"
                                    />
                                  </div>
                                  <div className="col-4 ps-4">
                                    <h5 className={`${style.namePayment}`}>
                                      Gopay
                                    </h5>
                                  </div>
                                  <div className="col-5 text-end">
                                    <input
                                      className={`form-check-input ${style.check}`}
                                      type="checkbox"
                                      value=""
                                      id="flexCheckDefault"
                                    />
                                  </div>
                                </div>
                                {/* POS INDONESIA */}
                                <div
                                  className={`row d-flex align-items-center ${style.optionPayment}`}>
                                  <div className={`col-3`}>
                                    <img
                                      className={style.iconPos}
                                      src="/images/pos-indonesia.webp"
                                      alt="icon-navbar"
                                    />
                                  </div>
                                  <div className="col-6 ps-4">
                                    <h5 className={`${style.namePayment}`}>
                                      Pos Indonesia
                                    </h5>
                                  </div>
                                  <div className="col-3 text-end">
                                    <input
                                      className={`form-check-input ${style.check}`}
                                      type="checkbox"
                                      value=""
                                      id="flexCheckDefault"
                                    />
                                  </div>
                                </div>
                                {/* MASTERCARD */}
                                <div
                                  className={`row mt-3 d-flex align-items-center ${style.optionPayment}`}>
                                  <div className={`col-3`}>
                                    <img
                                      className={style.iconMastercard}
                                      src="/images/mastercard.webp"
                                      alt="icon-navbar"
                                    />
                                  </div>
                                  <div className="col-4 ps-4">
                                    <h5 className={`${style.namePayment}`}>
                                      Mastercard
                                    </h5>
                                  </div>
                                  <div className="col-5 text-end">
                                    <input
                                      className={`form-check-input ${style.check}`}
                                      type="checkbox"
                                      value=""
                                      id="flexCheckDefault"
                                    />
                                  </div>
                                </div>
                              </div>
                              {/* TOTAL */}
                              <div className={`py-4 px-2 ${style.total}`}>
                                <h5>Shopping summary</h5>
                                <div className="row mt-4">
                                  <div className="col-6">
                                    <p className={style.orderDelivery}>Order</p>
                                  </div>
                                  <div className="col-6 text-end">
                                    <h5>Rp.250000</h5>
                                  </div>
                                </div>
                                <div className={`row ${style.delivery}`}>
                                  <div className="col-6">
                                    <p className={style.orderDelivery}>
                                      Delivery
                                    </p>
                                  </div>
                                  <div className="col-6 text-end">
                                    <h5>Rp.15000</h5>
                                  </div>
                                </div>
                              </div>
                            </div>

                            {/* FOOTER MDOAL */}
                            <div
                              className={`modal-footer d-block ${style.footer}`}>
                              <div className="row p-0 d-flex align-items-center">
                                <div className="col-6">
                                  <h4
                                    className="d-block"
                                    style={{ fontSize: "17px" }}>
                                    Shopping summary
                                  </h4>
                                  <h5 className={`${style.total}`}>
                                    Rp.265000
                                  </h5>
                                </div>
                                <div className="col-6 text-end">
                                  <button
                                    type="button"
                                    className={`btn btn-secondary ${style.btnBuy}`}
                                    data-bs-dismiss="modal">
                                    Buy
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          {/* END OF MY BAG */}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const token = getCookie("token", context) || "";

  const profileData = await axios.get(
    `${process.env.NEXT_PUBLIC_BACKEND_URL}/customer/detail`,
    {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    }
  );

  // console.log(profileData.data);
  return {
    props: {
      token,
      profileData: profileData.data,
    },
  };
}
