/* eslint-disable @next/next/no-img-element */
import React, { Component } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import style from "@/styles/pages/homeStyle.module.scss";
import Link from "next/link";
import Navbar from "@/components/organisms/navbar";
import CardProductNew from "@/components/molecules/cardProductNew";
import CardProductPopular from "@/components/molecules/cardProductPopular";
import Footer from "@/components/organisms/footer";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
  const productListNew = props.productListNew;
  const productListPopular = props.productListPopular;

  const [productNew, setProductNew] = React.useState(productListNew.data);
  const [productPopular, setProductPopular] = React.useState(
    productListPopular.data
  );

  // SORT BY CATEGORY
  const fetchBySort = (sortValue) => {
    if (sortValue) {
    }

    axios
      .get(
        `${process.env.NEXT_PUBLIC_BACKEND_URL}/products?sort=DESC&categoryFilter=${sortValue}`
      )
      .then(({ data }) => {
        setProductNew(data?.data);
        console.log(data?.data);
      })
      .catch((err) => {
        // setProductNew("");
      });
    // .finally(() => setIsLoading(false));
  };

  // SORT BY CATEGORY
  const fetchByColor = (sortValue) => {
    if (sortValue) {
    }

    axios
      .get(
        `${process.env.NEXT_PUBLIC_BACKEND_URL}/products?sort=DESC&colorFilter=${sortValue}`
      )
      .then(({ data }) => {
        setProductNew(data?.data);
        console.log(data?.data);
      })
      .catch((err) => {
        // setProductNew("");
      });
    // .finally(() => setIsLoading(false));
  };

  return (
    <>
      <Head>
        <title>Home | Blanja</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <div className="container-fluid p-0">
          {/* NAVBAR */}
          <nav
            className={`container-fluid sticky-sm-top shadow py-2 ${style.containerNavbar}`}
          >
            <Navbar />
          </nav>
          {/* END OF NAVBAR */}

          {/* PROMOTION */}
          <section className={`container mt-5 ${style.category1}`}>
            <div className={style.item}>
              <img
                className={style.icon}
                src="/images/Card-Promotion.webp"
                alt="icon-navbar"
              />
            </div>
            <div className={style.item}>
              <img
                className={style.icon}
                src="/images/Card-Promotion2.webp"
                alt="icon-navbar"
                onClick={() => fetchByColor("black")}
                onChange={(e) => {
                  fetchByColor(e.target.value);
                }}
              />
            </div>
            <div className={style.item}>
              <img
                className={style.icon}
                src="/images/Card-Promotion.webp"
                alt="icon-navbar"
              />
            </div>
            <div className={style.item}>
              <img
                className={style.icon}
                src="/images/Card-Promotion2.webp"
                alt="icon-navbar"
              />
            </div>
            <div className={style.item}>
              <img
                className={style.icon}
                src="/images/Card-Promotion.webp"
                alt="icon-navbar"
              />
            </div>
            <div className={style.item}>
              <img
                className={style.icon}
                src="/images/Card-Promotion2.webp"
                alt="icon-navbar"
              />
            </div>
          </section>
          {/* END OF PROMOTION */}

          {/* CATEGORY */}
          <section className={`container mt-5 ${style.category2}`}>
            <div className={`${style.subTitle}`}>
              <h2>Category</h2>
              <p>What are you currently looking for</p>
            </div>
            <div className={`${style.content}`}>
              <div className={style.item}>
                <img
                  className={style.icon}
                  src="/images/t-shirt.webp"
                  alt="icon-navbar"
                  onClick={() => fetchBySort("tshirt")}
                  onChange={(e) => {
                    fetchBySort(e.target.value);
                  }}
                />
              </div>
              <div className={style.item}>
                <img
                  className={style.icon}
                  src="/images/shorts.webp"
                  alt="icon-navbar"
                  onClick={() => fetchBySort("shorts")}
                  onChange={(e) => {
                    fetchBySort(e.target.value);
                  }}
                />
              </div>
              <div className={style.item}>
                <img
                  className={style.icon}
                  src="/images/bag.png"
                  alt="icon-navbar"
                  onClick={() => fetchBySort("bag")}
                  onChange={(e) => {
                    fetchBySort(e.target.value);
                  }}
                />
              </div>
              <div className={style.item}>
                <img
                  className={style.icon}
                  src="/images/pants.webp"
                  alt="icon-navbar"
                  onClick={() => fetchBySort("tshirt")}
                  onChange={(e) => {
                    fetchBySort(e.target.value);
                  }}
                />
              </div>
              <div className={style.item}>
                <img
                  className={style.icon}
                  src="/images/shoes.webp"
                  alt="icon-navbar"
                  onClick={() => fetchBySort("tshirt")}
                  onChange={(e) => {
                    fetchBySort(e.target.value);
                  }}
                />
              </div>
            </div>
          </section>
          {/* END OF CATEGORY */}

          {/* NEW PRODUCT */}
          <section className={`container mt-5 ${style.Product}`}>
            <div className={`${style.subTitle}`}>
              <h2>New</h2>
              <p>You’ve never seen it before!</p>
            </div>
            <div className={`row ${style.content}`}>
              {/* <div className="col-3">
                <CardProduct />
              </div> */}
              {productNew.length === 0 ? (
                <h2 className="text-center">Sorry, No Data Found</h2>
              ) : (
                productNew?.map((item, key) => (
                  <React.Fragment key={key}>
                    <div className="col-3 mb-4">
                      <CardProductNew
                        img={item?.products_picture[0]?.product_picture}
                        productName={item?.product_name}
                        price={item?.price}
                        storeName={item?.store_name}
                      />
                    </div>
                  </React.Fragment>
                ))
              )}
            </div>
          </section>
          {/* END OF NEW PRODUCT */}

          {/* POPULAR */}
          <section className={`container mt-5 mb-5 ${style.Product}`}>
            <div className={`${style.subTitle}`}>
              <h2>Popular</h2>
              <p>Find clothes that are trending recently</p>
            </div>
            <div className={`row ${style.content}`}>
              {productPopular?.map((item, key) => (
                <React.Fragment key={key}>
                  <div className="col-3 mb-4">
                    <CardProductPopular
                      // photo={item?.products_picture?.product_picture}
                      // img={() => {
                      //   const picture = item?.products_picture?.product_picture;

                      //   picture.includes("https")
                      //     ? picture
                      //     : "https://res.cloudinary.com/daouvimjz/image/upload/v1676279237/" +
                      //       picture;
                      // }}
                      // img={
                      //   item?.products_picture?.product_picture.includes(
                      //     "https"
                      //   )
                      //     ? item?.products_picture?.product_picture
                      //     : "https://res.cloudinary.com/daouvimjz/image/upload/v1676279237/" +
                      //       item?.products_picture?.product_picture
                      // }
                      img={item?.products_picture[0]?.product_picture}
                      productName={item?.product_name}
                      price={item?.price}
                      storeName={item?.store_name}
                    />
                  </div>
                </React.Fragment>
              ))}
            </div>
          </section>
          {/* END OF POPULAR */}

          {/* FOOTER */}
          <Footer />
          {/* END OF FOOTER */}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const productNew = await axios.get(
    `${process.env.NEXT_PUBLIC_BACKEND_URL}/products?page=1&limit=12&sort=DESC`
  );

  const productPopular = await axios.get(
    `${process.env.NEXT_PUBLIC_BACKEND_URL}/products?page=1&limit=12&orderBy=popular`
  );

  const convertProductNew = productNew.data;
  const convertProductPopular = productPopular.data;

  return {
    props: {
      productListNew: convertProductNew,
      productListPopular: convertProductPopular,
    }, // will be passed to the page component as props
  };
}
