/* eslint-disable @next/next/no-img-element */
import React, { Component } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import style from "@/styles/pages/homeStyle.module.scss";
import Link from "next/link";
import Navbar from "@/components/organisms/navbar";
import CardProduct from "@/components/molecules/cardProduct";
import Footer from "@/components/organisms/footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Blanja</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <div className="container-fluid p-0">
          {/* NAVBAR */}
          <nav
            className={`container-fluid sticky-sm-top shadow py-2 ${style.containerNavbar}`}
          >
            <Navbar />
          </nav>
          {/* END OF NAVBAR */}

          {/* PROMOTION */}
          <section className={`container mt-5 ${style.category1}`}>
            <div className={style.item}>
              <img
                className={style.icon}
                src="/images/Card-Promotion.webp"
                alt="icon-navbar"
              />
            </div>
            <div className={style.item}>
              <img
                className={style.icon}
                src="/images/Card-Promotion2.webp"
                alt="icon-navbar"
              />
            </div>
            <div className={style.item}>
              <img
                className={style.icon}
                src="/images/Card-Promotion.webp"
                alt="icon-navbar"
              />
            </div>
            <div className={style.item}>
              <img
                className={style.icon}
                src="/images/Card-Promotion2.webp"
                alt="icon-navbar"
              />
            </div>
            <div className={style.item}>
              <img
                className={style.icon}
                src="/images/Card-Promotion.webp"
                alt="icon-navbar"
              />
            </div>
            <div className={style.item}>
              <img
                className={style.icon}
                src="/images/Card-Promotion2.webp"
                alt="icon-navbar"
              />
            </div>
          </section>
          {/* END OF PROMOTION */}

          {/* CATEGORY */}
          <section className={`container mt-5 ${style.category2}`}>
            <div className={`${style.subTitle}`}>
              <h2>Category</h2>
              <p>What are you currently looking for</p>
            </div>
            <div className={`${style.content}`}>
              <div className={style.item}>
                <img
                  className={style.icon}
                  src="/images/t-shirt.webp"
                  alt="icon-navbar"
                />
              </div>
              <div className={style.item}>
                <img
                  className={style.icon}
                  src="/images/shorts.webp"
                  alt="icon-navbar"
                />
              </div>
              <div className={style.item}>
                <img
                  className={style.icon}
                  src="/images/jacket.webp"
                  alt="icon-navbar"
                />
              </div>
              <div className={style.item}>
                <img
                  className={style.icon}
                  src="/images/pants.webp"
                  alt="icon-navbar"
                />
              </div>
              <div className={style.item}>
                <img
                  className={style.icon}
                  src="/images/shoes.webp"
                  alt="icon-navbar"
                />
              </div>
            </div>
          </section>
          {/* END OF CATEGORY */}

          {/* NEW PRODUCT */}
          <section className={`container mt-5 ${style.Product}`}>
            <div className={`${style.subTitle}`}>
              <h2>New</h2>
              <p>You’ve never seen it before!</p>
            </div>
            <div className={`row ${style.content}`}>
              <div className="col-3">
                <CardProduct />
              </div>
              <div className="col-3">
                <CardProduct />
              </div>
              <div className="col-3">
                <CardProduct />
              </div>
              <div className="col-3">
                <CardProduct />
              </div>
            </div>
          </section>
          {/* END OF NEW PRODUCT */}

          {/* POPULAR */}
          <section className={`container mt-5 mb-5 ${style.Product}`}>
            <div className={`${style.subTitle}`}>
              <h2>Popular</h2>
              <p>Find clothes that are trending recently</p>
            </div>
            <div className={`row ${style.content}`}>
              <div className="col-3">
                <CardProduct />
              </div>
              <div className="col-3">
                <CardProduct />
              </div>
              <div className="col-3">
                <CardProduct />
              </div>
              <div className="col-3">
                <CardProduct />
              </div>
            </div>
          </section>
          {/* END OF POPULAR */}

          {/* FOOTER */}
          <Footer />
          {/* END OF FOOTER */}
        </div>
      </main>
    </>
  );
}
